services:
    jms_serializer.camel_case_naming_strategy:
        class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
        public: false

    ongr_api.elasticsearch_loader:
        class: ONGR\ApiBundle\Routing\ElasticsearchLoader
        arguments: [%ongr_api.versions%]
        tags:
            - { name: routing.loader }

    ongr_api.crud:
        class: ONGR\ApiBundle\Service\Crud

    ongr_api.rest_controller:
        class: ONGR\ApiBundle\Controller\RestController

    ongr_api.request_serializer:
        class: ONGR\ApiBundle\Service\RequestSerializer
        arguments:
            - "@serializer"
            - %ongr_api.default_encoding%

    ongr_api.field_validator:
        class: ONGR\ApiBundle\Service\FieldValidator
        arguments:
            - "@es.manager"
            - %ongr_api.versions%

    ongr_api.batch_request_handler:
        class: ONGR\ApiBundle\Service\BatchRequestHandler
        arguments:
            - "@ongr_api.crud"
            - "@es.manager"
            - "@ongr_api.request_serializer"