parameters:
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
    ongr_api.elasticsearch_loader.class: ONGR\ApiBundle\Routing\ElasticsearchLoader

    ongr_api.form.float_type.class: ONGR\ApiBundle\Form\FloatType
    ongr_api.form.string_type.class: ONGR\ApiBundle\Form\StringType
    ongr_api.form.geo_point_type.class: ONGR\ApiBundle\Form\GeoPointType
    ongr_api.form.completion_type.class: ONGR\ApiBundle\Form\CompletionType
    ongr_api.form.object_type.class: ONGR\ApiBundle\Form\ObjectType
    ongr_api.form.nested_type.class: ONGR\ApiBundle\Form\NestedType

    ongr_api.form.document_type.class: ONGR\ApiBundle\Form\DocumentType
    ongr_api.form.document_type_factory.class: ONGR\ApiBundle\Form\DocumentTypeFactory

services:
    ongr_api.elasticsearch_loader:
        class: %ongr_api.elasticsearch_loader.class%
        calls:
            - [setCollection, [@ongr_api.route_collection]]
        tags:
            - { name: routing.loader }

    ongr_api.document_type_factory:
        class: %ongr_api.form.document_type_factory.class%
        arguments:
            - @service_container
        public: false

    ongr_api.document_type:
        class: %ongr_api.form.document_type.class%
        factory: ["@ongr_api.document_type_factory", get]
        tags:
            - { name: form.type, alias: ongr_api_document_type }

    ongr_api.form.string_type:
        class: %ongr_api.form.string_type.class%
        tags:
            - { name: form.type, alias: string }

    ongr_api.form.geo_point_type:
        class: %ongr_api.form.geo_point_type.class%
        tags:
            - { name: form.type, alias: geo_point }

    ongr_api.form.float_type:
        class: %ongr_api.form.float_type.class%
        tags:
            - { name: form.type, alias: float }

    ongr_api.form.completion_type:
        class: %ongr_api.form.completion_type.class%
        tags:
            - { name: form.type, alias: completion }

    ongr_api.form.object_type:
        class: %ongr_api.form.object_type.class%
        tags:
            - { name: form.type, alias: object }

    ongr_api.form.nested_type:
        class: %ongr_api.form.nested_type.class%
        tags:
            - { name: form.type, alias: nested }
