parameters:
    jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

    ongr_api.elasticsearch_loader.class: ONGR\ApiBundle\Routing\ElasticsearchLoader
    ongr_api.route_collection.class: ONGR\ApiBundle\Routing\ApiRouteCollection

    ongr_api.rest_request.class: ONGR\ApiBundle\Request\RestRequest
    ongr_api.rest_response_view_handler.class: ONGR\ApiBundle\Response\ViewHandler
    ongr_api.crud.class: ONGR\ApiBundle\Service\Crud
    ongr_api.rest_controller.class: ONGR\ApiBundle\Controller\RestController
    ongr_api.command_controller.class: ONGR\ApiBundle\Controller\CommandController

    ongr_api.event_listener.rest_request.class: ONGR\ApiBundle\EventListener\RestRequestEventListener
    ongr_api.event_listener.rest_exception.class: ONGR\ApiBundle\EventListener\RestExceptionListener

services:
    ongr_api.route_collection:
        class: %ongr_api.route_collection.class%
        public: false
        arguments:
            - @service_container
        calls:
            - [collectRoutes]

    ongr_api.elasticsearch_loader:
        class: %ongr_api.elasticsearch_loader.class%
        calls:
            - [setCollection, [@ongr_api.route_collection]]
        tags:
            - { name: routing.loader }

    ongr_api.rest_response_view_handler:
        class: %ongr_api.rest_response_view_handler.class%
        arguments:
            - @ongr_api.rest_request

    ongr_api.event_listener.rest_request:
        class: %ongr_api.event_listener.rest_request.class%
        arguments:
            - @ongr_api.rest_request
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }

    ongr_api.event_listener.rest_exception:
        class: %ongr_api.event_listener.rest_exception.class%
        arguments:
            - @ongr_api.rest_request
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    ongr_api.rest_request:
        class: %ongr_api.rest_request.class%
        arguments:
            - @service_container

    ongr_api.crud:
        class: %ongr_api.crud.class%

    ongr_api.rest_controller:
        class: %ongr_api.rest_controller.class%

    ongr_api.command_controller:
        class: %ongr_api.command_controller.class%
