services:
    jms_serializer.camel_case_naming_strategy:
        class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy
        public: false

    ongr_api.route_collection:
        class: ONGR\ApiBundle\Routing\ApiRouteCollection
        public: false
        arguments:
            - "@service_container"
        calls:
            - [collectRoutes]

    ongr_api.elasticsearch_loader:
        class: ONGR\ApiBundle\Routing\ElasticsearchLoader
        calls:
            - [setCollection, ["@ongr_api.route_collection"]]
        tags:
            - { name: routing.loader }

    ongr_api.crud:
        class: ONGR\ApiBundle\Service\Crud

    ongr_api.rest_controller:
        class: ONGR\ApiBundle\Controller\RestController

    ongr_api.request_serializer:
        class: ONGR\ApiBundle\Service\RequestSerializer
        arguments:
            - "@serializer"
            - %ongr_api.default_encoding%
